/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CompradorRouteImport } from './routes/comprador'
import { Route as EsqueciMinhaSenhaRouteImport } from './routes/esqueci-minha-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as VeiculosRouteImport } from './routes/veiculos'
import { Route as VendedorRouteImport } from './routes/vendedor'
import { Route as VenderRouteImport } from './routes/vender'
import { Route as VistoriadorRouteImport } from './routes/vistoriador'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnunciosRouteImport } from './routes/admin/anuncios'
import { Route as AdminCompradoresRouteImport } from './routes/admin/compradores'
import { Route as AdminComunicacoesRouteImport } from './routes/admin/comunicacoes'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminContratosRouteImport } from './routes/admin/contratos'
import { Route as AdminConversasRouteImport } from './routes/admin/conversas'
import { Route as AdminDemoRouteImport } from './routes/admin/demo'
import { Route as AdminEntregasRouteImport } from './routes/admin/entregas'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminMapaRouteImport } from './routes/admin/mapa'
import { Route as AdminNegociacoesRouteImport } from './routes/admin/negociacoes'
import { Route as AdminPagamentosRouteImport } from './routes/admin/pagamentos'
import { Route as AdminRelatoriosRouteImport } from './routes/admin/relatorios'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AdminVeiculosRouteImport } from './routes/admin/veiculos'
import { Route as AdminVendedoresRouteImport } from './routes/admin/vendedores'
import { Route as AdminVistoriasRouteImport } from './routes/admin/vistorias'
import { Route as CompradorIndexRouteImport } from './routes/comprador/index'
import { Route as CompradorCadastroRouteImport } from './routes/comprador.cadastro'
import { Route as CompradorDocumentosRouteImport } from './routes/comprador/documentos'
import { Route as CompradorInteressesRouteImport } from './routes/comprador/interesses'
import { Route as CompradorNegociacoesRouteImport } from './routes/comprador/negociacoes'
import { Route as CompradorPerfilRouteImport } from './routes/comprador/perfil'
import { Route as VeiculosIndexRouteImport } from './routes/veiculos.index'
import { Route as VeiculosSlugRouteImport } from './routes/veiculos.$slug'
import { Route as VendedorIndexRouteImport } from './routes/vendedor.index'
import { Route as VendedorBoasVindasRouteImport } from './routes/vendedor.boas-vindas'
import { Route as VendedorCadastrarRouteImport } from './routes/vendedor.cadastrar'
import { Route as VendedorContratoRouteImport } from './routes/vendedor.contrato'
import { Route as VendedorDocumentosRouteImport } from './routes/vendedor.documentos'
import { Route as VendedorFinanceiroRouteImport } from './routes/vendedor.financeiro'
import { Route as VendedorOnboardingRouteImport } from './routes/vendedor.onboarding'
import { Route as VendedorPerfilRouteImport } from './routes/vendedor.perfil'
import { Route as VendedorVeiculosRouteImport } from './routes/vendedor.veiculos'
import { Route as VistoriadorIndexRouteImport } from './routes/vistoriador.index'
import { Route as VistoriadorAgendaRouteImport } from './routes/vistoriador.agenda'
import { Route as VistoriadorHistoricoRouteImport } from './routes/vistoriador.historico'
import { Route as VistoriadorPerfilRouteImport } from './routes/vistoriador.perfil'
import { Route as AdminAnaliseVistoriaIdRouteImport } from './routes/admin/analise-vistoria.$id'
import { Route as AdminCompradorIdRouteImport } from './routes/admin/comprador.$id'
import { Route as AdminContratoIdRouteImport } from './routes/admin/contrato.$id'
import { Route as AdminLeiloesIndexRouteImport } from './routes/admin/leiloes.index'
import { Route as AdminLeiloesIdRouteImport } from './routes/admin/leiloes.$id'
import { Route as AdminNegociacaoIdRouteImport } from './routes/admin/negociacao.$id'
import { Route as AdminPagamentoIdRouteImport } from './routes/admin/pagamento.$id'
import { Route as AdminVeiculoIdRouteImport } from './routes/admin/veiculo.$id'
import { Route as AdminVendedorIdRouteImport } from './routes/admin/vendedor.$id'
import { Route as ApiPublicUploadRouteImport } from './routes/api/public/upload'
import { Route as CompradorEntregaIdRouteImport } from './routes/comprador/entrega.$id'
import { Route as CompradorPagamentoIdRouteImport } from './routes/comprador/pagamento.$id'
import { Route as VendedorEntregaIdRouteImport } from './routes/vendedor.entrega.$id'
import { Route as VendedorVeiculoRouteImport } from './routes/vendedor.veiculo.'
import { Route as VendedorVeiculoIdRouteImport } from './routes/vendedor.veiculo.$id'
import { Route as VendedorVeiculoPropostaRouteImport } from './routes/vendedor.veiculo..proposta'
import { Route as VistoriadorExecucaoIdRouteImport } from './routes/vistoriador.execucao.$id'
import { Route as VistoriadorVistoriaIdRouteImport } from './routes/vistoriador.vistoria.$id'
import { Route as AdminAnunciosNovoRouteImport } from './routes/admin/anuncios.novo.'
import { Route as AdminVeiculoIdPosVistoriaRouteImport } from './routes/admin/veiculo.$id.pos-vistoria'
import { Route as ApiPublicWebhooksPagamentosRouteImport } from './routes/api/public/webhooks/pagamentos'
import { Route as ApiPublicWebhooksWhatsappRouteImport } from './routes/api/public/webhooks/whatsapp'
import { Route as VendedorVeiculoIdPropostaRouteImport } from './routes/vendedor.veiculo.$id.proposta'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CompradorRoute = CompradorRouteImport.update({
  id: '/comprador',
  path: '/comprador',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciMinhaSenhaRoute = EsqueciMinhaSenhaRouteImport.update({
  id: '/esqueci-minha-senha',
  path: '/esqueci-minha-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosRoute = VeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const VendedorRoute = VendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const VenderRoute = VenderRouteImport.update({
  id: '/vender',
  path: '/vender',
  getParentRoute: () => rootRouteImport,
} as any)
const VistoriadorRoute = VistoriadorRouteImport.update({
  id: '/vistoriador',
  path: '/vistoriador',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnunciosRoute = AdminAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompradoresRoute = AdminCompradoresRouteImport.update({
  id: '/compradores',
  path: '/compradores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComunicacoesRoute = AdminComunicacoesRouteImport.update({
  id: '/comunicacoes',
  path: '/comunicacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContratosRoute = AdminContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConversasRoute = AdminConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemoRoute = AdminDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntregasRoute = AdminEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapaRoute = AdminMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNegociacoesRoute = AdminNegociacoesRouteImport.update({
  id: '/negociacoes',
  path: '/negociacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVeiculosRoute = AdminVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendedoresRoute = AdminVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVistoriasRoute = AdminVistoriasRouteImport.update({
  id: '/vistorias',
  path: '/vistorias',
  getParentRoute: () => AdminRoute,
} as any)
const CompradorIndexRoute = CompradorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompradorRoute,
} as any)
const CompradorCadastroRoute = CompradorCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => CompradorRoute,
} as any)
const CompradorDocumentosRoute = CompradorDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => CompradorRoute,
} as any)
const CompradorInteressesRoute = CompradorInteressesRouteImport.update({
  id: '/interesses',
  path: '/interesses',
  getParentRoute: () => CompradorRoute,
} as any)
const CompradorNegociacoesRoute = CompradorNegociacoesRouteImport.update({
  id: '/negociacoes',
  path: '/negociacoes',
  getParentRoute: () => CompradorRoute,
} as any)
const CompradorPerfilRoute = CompradorPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => CompradorRoute,
} as any)
const VeiculosIndexRoute = VeiculosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VeiculosRoute,
} as any)
const VeiculosSlugRoute = VeiculosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VeiculosRoute,
} as any)
const VendedorIndexRoute = VendedorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendedorRoute,
} as any)
const VendedorBoasVindasRoute = VendedorBoasVindasRouteImport.update({
  id: '/boas-vindas',
  path: '/boas-vindas',
  getParentRoute: () => VendedorRoute,
} as any)
const VendedorCadastrarRoute = VendedorCadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => VendedorRoute,
} as any)
const VendedorContratoRoute = VendedorContratoRouteImport.update({
  id: '/contrato',
  path: '/contrato',
  getParentRoute: () => VendedorRoute,
} as any)
const VendedorDocumentosRoute = VendedorDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => VendedorRoute,
} as any)
const VendedorFinanceiroRoute = VendedorFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => VendedorRoute,
} as any)
const VendedorOnboardingRoute = VendedorOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => VendedorRoute,
} as any)
const VendedorPerfilRoute = VendedorPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => VendedorRoute,
} as any)
const VendedorVeiculosRoute = VendedorVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => VendedorRoute,
} as any)
const VistoriadorIndexRoute = VistoriadorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VistoriadorRoute,
} as any)
const VistoriadorAgendaRoute = VistoriadorAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => VistoriadorRoute,
} as any)
const VistoriadorHistoricoRoute = VistoriadorHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => VistoriadorRoute,
} as any)
const VistoriadorPerfilRoute = VistoriadorPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => VistoriadorRoute,
} as any)
const AdminAnaliseVistoriaIdRoute = AdminAnaliseVistoriaIdRouteImport.update({
  id: '/analise-vistoria/$id',
  path: '/analise-vistoria/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompradorIdRoute = AdminCompradorIdRouteImport.update({
  id: '/comprador/$id',
  path: '/comprador/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContratoIdRoute = AdminContratoIdRouteImport.update({
  id: '/contrato/$id',
  path: '/contrato/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeiloesIndexRoute = AdminLeiloesIndexRouteImport.update({
  id: '/leiloes/',
  path: '/leiloes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeiloesIdRoute = AdminLeiloesIdRouteImport.update({
  id: '/leiloes/$id',
  path: '/leiloes/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNegociacaoIdRoute = AdminNegociacaoIdRouteImport.update({
  id: '/negociacao/$id',
  path: '/negociacao/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentoIdRoute = AdminPagamentoIdRouteImport.update({
  id: '/pagamento/$id',
  path: '/pagamento/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVeiculoIdRoute = AdminVeiculoIdRouteImport.update({
  id: '/veiculo/$id',
  path: '/veiculo/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendedorIdRoute = AdminVendedorIdRouteImport.update({
  id: '/vendedor/$id',
  path: '/vendedor/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicUploadRoute = ApiPublicUploadRouteImport.update({
  id: '/api/public/upload',
  path: '/api/public/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CompradorEntregaIdRoute = CompradorEntregaIdRouteImport.update({
  id: '/entrega/$id',
  path: '/entrega/$id',
  getParentRoute: () => CompradorRoute,
} as any)
const CompradorPagamentoIdRoute = CompradorPagamentoIdRouteImport.update({
  id: '/pagamento/$id',
  path: '/pagamento/$id',
  getParentRoute: () => CompradorRoute,
} as any)
const VendedorEntregaIdRoute = VendedorEntregaIdRouteImport.update({
  id: '/entrega/$id',
  path: '/entrega/$id',
  getParentRoute: () => VendedorRoute,
} as any)
const VendedorVeiculoRoute = VendedorVeiculoRouteImport.update({
  id: '/veiculo/',
  path: '/veiculo/',
  getParentRoute: () => VendedorRoute,
} as any)
const VendedorVeiculoIdRoute = VendedorVeiculoIdRouteImport.update({
  id: '/veiculo/$id',
  path: '/veiculo/$id',
  getParentRoute: () => VendedorRoute,
} as any)
const VendedorVeiculoPropostaRoute = VendedorVeiculoPropostaRouteImport.update({
  id: '/veiculo/proposta',
  path: '/veiculo/proposta',
  getParentRoute: () => VendedorRoute,
} as any)
const VistoriadorExecucaoIdRoute = VistoriadorExecucaoIdRouteImport.update({
  id: '/execucao/$id',
  path: '/execucao/$id',
  getParentRoute: () => VistoriadorRoute,
} as any)
const VistoriadorVistoriaIdRoute = VistoriadorVistoriaIdRouteImport.update({
  id: '/vistoria/$id',
  path: '/vistoria/$id',
  getParentRoute: () => VistoriadorRoute,
} as any)
const AdminAnunciosNovoRoute = AdminAnunciosNovoRouteImport.update({
  id: '/novo/',
  path: '/novo/',
  getParentRoute: () => AdminAnunciosRoute,
} as any)
const AdminVeiculoIdPosVistoriaRoute =
  AdminVeiculoIdPosVistoriaRouteImport.update({
    id: '/pos-vistoria',
    path: '/pos-vistoria',
    getParentRoute: () => AdminVeiculoIdRoute,
  } as any)
const ApiPublicWebhooksPagamentosRoute =
  ApiPublicWebhooksPagamentosRouteImport.update({
    id: '/api/public/webhooks/pagamentos',
    path: '/api/public/webhooks/pagamentos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksWhatsappRoute =
  ApiPublicWebhooksWhatsappRouteImport.update({
    id: '/api/public/webhooks/whatsapp',
    path: '/api/public/webhooks/whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const VendedorVeiculoIdPropostaRoute =
  VendedorVeiculoIdPropostaRouteImport.update({
    id: '/proposta',
    path: '/proposta',
    getParentRoute: () => VendedorVeiculoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/comprador': typeof CompradorRouteWithChildren
  '/esqueci-minha-senha': typeof EsqueciMinhaSenhaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/veiculos': typeof VeiculosRouteWithChildren
  '/vendedor': typeof VendedorRouteWithChildren
  '/vender': typeof VenderRoute
  '/vistoriador': typeof VistoriadorRouteWithChildren
  '/admin/anuncios': typeof AdminAnunciosRouteWithChildren
  '/admin/compradores': typeof AdminCompradoresRoute
  '/admin/comunicacoes': typeof AdminComunicacoesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/contratos': typeof AdminContratosRoute
  '/admin/conversas': typeof AdminConversasRoute
  '/admin/demo': typeof AdminDemoRoute
  '/admin/entregas': typeof AdminEntregasRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/mapa': typeof AdminMapaRoute
  '/admin/negociacoes': typeof AdminNegociacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/admin/vendedores': typeof AdminVendedoresRoute
  '/admin/vistorias': typeof AdminVistoriasRoute
  '/comprador/cadastro': typeof CompradorCadastroRoute
  '/comprador/documentos': typeof CompradorDocumentosRoute
  '/comprador/interesses': typeof CompradorInteressesRoute
  '/comprador/negociacoes': typeof CompradorNegociacoesRoute
  '/comprador/perfil': typeof CompradorPerfilRoute
  '/veiculos/$slug': typeof VeiculosSlugRoute
  '/vendedor/boas-vindas': typeof VendedorBoasVindasRoute
  '/vendedor/cadastrar': typeof VendedorCadastrarRoute
  '/vendedor/contrato': typeof VendedorContratoRoute
  '/vendedor/documentos': typeof VendedorDocumentosRoute
  '/vendedor/financeiro': typeof VendedorFinanceiroRoute
  '/vendedor/onboarding': typeof VendedorOnboardingRoute
  '/vendedor/perfil': typeof VendedorPerfilRoute
  '/vendedor/veiculos': typeof VendedorVeiculosRoute
  '/vistoriador/agenda': typeof VistoriadorAgendaRoute
  '/vistoriador/historico': typeof VistoriadorHistoricoRoute
  '/vistoriador/perfil': typeof VistoriadorPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/comprador/': typeof CompradorIndexRoute
  '/veiculos/': typeof VeiculosIndexRoute
  '/vendedor/': typeof VendedorIndexRoute
  '/vistoriador/': typeof VistoriadorIndexRoute
  '/vendedor/veiculo/': typeof VendedorVeiculoRoute
  '/admin/analise-vistoria/$id': typeof AdminAnaliseVistoriaIdRoute
  '/admin/comprador/$id': typeof AdminCompradorIdRoute
  '/admin/contrato/$id': typeof AdminContratoIdRoute
  '/admin/leiloes/$id': typeof AdminLeiloesIdRoute
  '/admin/negociacao/$id': typeof AdminNegociacaoIdRoute
  '/admin/pagamento/$id': typeof AdminPagamentoIdRoute
  '/admin/veiculo/$id': typeof AdminVeiculoIdRouteWithChildren
  '/admin/vendedor/$id': typeof AdminVendedorIdRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/comprador/entrega/$id': typeof CompradorEntregaIdRoute
  '/comprador/pagamento/$id': typeof CompradorPagamentoIdRoute
  '/vendedor/entrega/$id': typeof VendedorEntregaIdRoute
  '/vendedor/veiculo/$id': typeof VendedorVeiculoIdRouteWithChildren
  '/vendedor/veiculo/proposta': typeof VendedorVeiculoPropostaRoute
  '/vistoriador/execucao/$id': typeof VistoriadorExecucaoIdRoute
  '/vistoriador/vistoria/$id': typeof VistoriadorVistoriaIdRoute
  '/admin/leiloes/': typeof AdminLeiloesIndexRoute
  '/admin/anuncios/novo/': typeof AdminAnunciosNovoRoute
  '/admin/veiculo/$id/pos-vistoria': typeof AdminVeiculoIdPosVistoriaRoute
  '/api/public/webhooks/pagamentos': typeof ApiPublicWebhooksPagamentosRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
  '/vendedor/veiculo/$id/proposta': typeof VendedorVeiculoIdPropostaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/esqueci-minha-senha': typeof EsqueciMinhaSenhaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/vender': typeof VenderRoute
  '/admin/anuncios': typeof AdminAnunciosRouteWithChildren
  '/admin/compradores': typeof AdminCompradoresRoute
  '/admin/comunicacoes': typeof AdminComunicacoesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/contratos': typeof AdminContratosRoute
  '/admin/conversas': typeof AdminConversasRoute
  '/admin/demo': typeof AdminDemoRoute
  '/admin/entregas': typeof AdminEntregasRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/mapa': typeof AdminMapaRoute
  '/admin/negociacoes': typeof AdminNegociacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/admin/vendedores': typeof AdminVendedoresRoute
  '/admin/vistorias': typeof AdminVistoriasRoute
  '/comprador/cadastro': typeof CompradorCadastroRoute
  '/comprador/documentos': typeof CompradorDocumentosRoute
  '/comprador/interesses': typeof CompradorInteressesRoute
  '/comprador/negociacoes': typeof CompradorNegociacoesRoute
  '/comprador/perfil': typeof CompradorPerfilRoute
  '/veiculos/$slug': typeof VeiculosSlugRoute
  '/vendedor/boas-vindas': typeof VendedorBoasVindasRoute
  '/vendedor/cadastrar': typeof VendedorCadastrarRoute
  '/vendedor/contrato': typeof VendedorContratoRoute
  '/vendedor/documentos': typeof VendedorDocumentosRoute
  '/vendedor/financeiro': typeof VendedorFinanceiroRoute
  '/vendedor/onboarding': typeof VendedorOnboardingRoute
  '/vendedor/perfil': typeof VendedorPerfilRoute
  '/vendedor/veiculos': typeof VendedorVeiculosRoute
  '/vistoriador/agenda': typeof VistoriadorAgendaRoute
  '/vistoriador/historico': typeof VistoriadorHistoricoRoute
  '/vistoriador/perfil': typeof VistoriadorPerfilRoute
  '/admin': typeof AdminIndexRoute
  '/comprador': typeof CompradorIndexRoute
  '/veiculos': typeof VeiculosIndexRoute
  '/vendedor': typeof VendedorIndexRoute
  '/vistoriador': typeof VistoriadorIndexRoute
  '/vendedor/veiculo': typeof VendedorVeiculoRoute
  '/admin/analise-vistoria/$id': typeof AdminAnaliseVistoriaIdRoute
  '/admin/comprador/$id': typeof AdminCompradorIdRoute
  '/admin/contrato/$id': typeof AdminContratoIdRoute
  '/admin/leiloes/$id': typeof AdminLeiloesIdRoute
  '/admin/negociacao/$id': typeof AdminNegociacaoIdRoute
  '/admin/pagamento/$id': typeof AdminPagamentoIdRoute
  '/admin/veiculo/$id': typeof AdminVeiculoIdRouteWithChildren
  '/admin/vendedor/$id': typeof AdminVendedorIdRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/comprador/entrega/$id': typeof CompradorEntregaIdRoute
  '/comprador/pagamento/$id': typeof CompradorPagamentoIdRoute
  '/vendedor/entrega/$id': typeof VendedorEntregaIdRoute
  '/vendedor/veiculo/$id': typeof VendedorVeiculoIdRouteWithChildren
  '/vendedor/veiculo/proposta': typeof VendedorVeiculoPropostaRoute
  '/vistoriador/execucao/$id': typeof VistoriadorExecucaoIdRoute
  '/vistoriador/vistoria/$id': typeof VistoriadorVistoriaIdRoute
  '/admin/leiloes': typeof AdminLeiloesIndexRoute
  '/admin/anuncios/novo': typeof AdminAnunciosNovoRoute
  '/admin/veiculo/$id/pos-vistoria': typeof AdminVeiculoIdPosVistoriaRoute
  '/api/public/webhooks/pagamentos': typeof ApiPublicWebhooksPagamentosRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
  '/vendedor/veiculo/$id/proposta': typeof VendedorVeiculoIdPropostaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/comprador': typeof CompradorRouteWithChildren
  '/esqueci-minha-senha': typeof EsqueciMinhaSenhaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/veiculos': typeof VeiculosRouteWithChildren
  '/vendedor': typeof VendedorRouteWithChildren
  '/vender': typeof VenderRoute
  '/vistoriador': typeof VistoriadorRouteWithChildren
  '/admin/anuncios': typeof AdminAnunciosRouteWithChildren
  '/admin/compradores': typeof AdminCompradoresRoute
  '/admin/comunicacoes': typeof AdminComunicacoesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/contratos': typeof AdminContratosRoute
  '/admin/conversas': typeof AdminConversasRoute
  '/admin/demo': typeof AdminDemoRoute
  '/admin/entregas': typeof AdminEntregasRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/mapa': typeof AdminMapaRoute
  '/admin/negociacoes': typeof AdminNegociacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/admin/vendedores': typeof AdminVendedoresRoute
  '/admin/vistorias': typeof AdminVistoriasRoute
  '/comprador/cadastro': typeof CompradorCadastroRoute
  '/comprador/documentos': typeof CompradorDocumentosRoute
  '/comprador/interesses': typeof CompradorInteressesRoute
  '/comprador/negociacoes': typeof CompradorNegociacoesRoute
  '/comprador/perfil': typeof CompradorPerfilRoute
  '/veiculos/$slug': typeof VeiculosSlugRoute
  '/vendedor/boas-vindas': typeof VendedorBoasVindasRoute
  '/vendedor/cadastrar': typeof VendedorCadastrarRoute
  '/vendedor/contrato': typeof VendedorContratoRoute
  '/vendedor/documentos': typeof VendedorDocumentosRoute
  '/vendedor/financeiro': typeof VendedorFinanceiroRoute
  '/vendedor/onboarding': typeof VendedorOnboardingRoute
  '/vendedor/perfil': typeof VendedorPerfilRoute
  '/vendedor/veiculos': typeof VendedorVeiculosRoute
  '/vistoriador/agenda': typeof VistoriadorAgendaRoute
  '/vistoriador/historico': typeof VistoriadorHistoricoRoute
  '/vistoriador/perfil': typeof VistoriadorPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/comprador/': typeof CompradorIndexRoute
  '/veiculos/': typeof VeiculosIndexRoute
  '/vendedor/': typeof VendedorIndexRoute
  '/vistoriador/': typeof VistoriadorIndexRoute
  '/vendedor/veiculo/': typeof VendedorVeiculoRoute
  '/admin/analise-vistoria/$id': typeof AdminAnaliseVistoriaIdRoute
  '/admin/comprador/$id': typeof AdminCompradorIdRoute
  '/admin/contrato/$id': typeof AdminContratoIdRoute
  '/admin/leiloes/$id': typeof AdminLeiloesIdRoute
  '/admin/negociacao/$id': typeof AdminNegociacaoIdRoute
  '/admin/pagamento/$id': typeof AdminPagamentoIdRoute
  '/admin/veiculo/$id': typeof AdminVeiculoIdRouteWithChildren
  '/admin/vendedor/$id': typeof AdminVendedorIdRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/comprador/entrega/$id': typeof CompradorEntregaIdRoute
  '/comprador/pagamento/$id': typeof CompradorPagamentoIdRoute
  '/vendedor/entrega/$id': typeof VendedorEntregaIdRoute
  '/vendedor/veiculo/$id': typeof VendedorVeiculoIdRouteWithChildren
  '/vendedor/veiculo/proposta': typeof VendedorVeiculoPropostaRoute
  '/vistoriador/execucao/$id': typeof VistoriadorExecucaoIdRoute
  '/vistoriador/vistoria/$id': typeof VistoriadorVistoriaIdRoute
  '/admin/leiloes/': typeof AdminLeiloesIndexRoute
  '/admin/anuncios/novo/': typeof AdminAnunciosNovoRoute
  '/admin/veiculo/$id/pos-vistoria': typeof AdminVeiculoIdPosVistoriaRoute
  '/api/public/webhooks/pagamentos': typeof ApiPublicWebhooksPagamentosRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
  '/vendedor/veiculo/$id/proposta': typeof VendedorVeiculoIdPropostaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/comprador'
    | '/esqueci-minha-senha'
    | '/login'
    | '/redefinir-senha'
    | '/veiculos'
    | '/vendedor'
    | '/vender'
    | '/vistoriador'
    | '/admin/anuncios'
    | '/admin/compradores'
    | '/admin/comunicacoes'
    | '/admin/configuracoes'
    | '/admin/contratos'
    | '/admin/conversas'
    | '/admin/demo'
    | '/admin/entregas'
    | '/admin/logs'
    | '/admin/mapa'
    | '/admin/negociacoes'
    | '/admin/pagamentos'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/admin/veiculos'
    | '/admin/vendedores'
    | '/admin/vistorias'
    | '/comprador/cadastro'
    | '/comprador/documentos'
    | '/comprador/interesses'
    | '/comprador/negociacoes'
    | '/comprador/perfil'
    | '/veiculos/$slug'
    | '/vendedor/boas-vindas'
    | '/vendedor/cadastrar'
    | '/vendedor/contrato'
    | '/vendedor/documentos'
    | '/vendedor/financeiro'
    | '/vendedor/onboarding'
    | '/vendedor/perfil'
    | '/vendedor/veiculos'
    | '/vistoriador/agenda'
    | '/vistoriador/historico'
    | '/vistoriador/perfil'
    | '/admin/'
    | '/comprador/'
    | '/veiculos/'
    | '/vendedor/'
    | '/vistoriador/'
    | '/vendedor/veiculo/'
    | '/admin/analise-vistoria/$id'
    | '/admin/comprador/$id'
    | '/admin/contrato/$id'
    | '/admin/leiloes/$id'
    | '/admin/negociacao/$id'
    | '/admin/pagamento/$id'
    | '/admin/veiculo/$id'
    | '/admin/vendedor/$id'
    | '/api/public/upload'
    | '/comprador/entrega/$id'
    | '/comprador/pagamento/$id'
    | '/vendedor/entrega/$id'
    | '/vendedor/veiculo/$id'
    | '/vendedor/veiculo/proposta'
    | '/vistoriador/execucao/$id'
    | '/vistoriador/vistoria/$id'
    | '/admin/leiloes/'
    | '/admin/anuncios/novo/'
    | '/admin/veiculo/$id/pos-vistoria'
    | '/api/public/webhooks/pagamentos'
    | '/api/public/webhooks/whatsapp'
    | '/vendedor/veiculo/$id/proposta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/esqueci-minha-senha'
    | '/login'
    | '/redefinir-senha'
    | '/vender'
    | '/admin/anuncios'
    | '/admin/compradores'
    | '/admin/comunicacoes'
    | '/admin/configuracoes'
    | '/admin/contratos'
    | '/admin/conversas'
    | '/admin/demo'
    | '/admin/entregas'
    | '/admin/logs'
    | '/admin/mapa'
    | '/admin/negociacoes'
    | '/admin/pagamentos'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/admin/veiculos'
    | '/admin/vendedores'
    | '/admin/vistorias'
    | '/comprador/cadastro'
    | '/comprador/documentos'
    | '/comprador/interesses'
    | '/comprador/negociacoes'
    | '/comprador/perfil'
    | '/veiculos/$slug'
    | '/vendedor/boas-vindas'
    | '/vendedor/cadastrar'
    | '/vendedor/contrato'
    | '/vendedor/documentos'
    | '/vendedor/financeiro'
    | '/vendedor/onboarding'
    | '/vendedor/perfil'
    | '/vendedor/veiculos'
    | '/vistoriador/agenda'
    | '/vistoriador/historico'
    | '/vistoriador/perfil'
    | '/admin'
    | '/comprador'
    | '/veiculos'
    | '/vendedor'
    | '/vistoriador'
    | '/vendedor/veiculo'
    | '/admin/analise-vistoria/$id'
    | '/admin/comprador/$id'
    | '/admin/contrato/$id'
    | '/admin/leiloes/$id'
    | '/admin/negociacao/$id'
    | '/admin/pagamento/$id'
    | '/admin/veiculo/$id'
    | '/admin/vendedor/$id'
    | '/api/public/upload'
    | '/comprador/entrega/$id'
    | '/comprador/pagamento/$id'
    | '/vendedor/entrega/$id'
    | '/vendedor/veiculo/$id'
    | '/vendedor/veiculo/proposta'
    | '/vistoriador/execucao/$id'
    | '/vistoriador/vistoria/$id'
    | '/admin/leiloes'
    | '/admin/anuncios/novo'
    | '/admin/veiculo/$id/pos-vistoria'
    | '/api/public/webhooks/pagamentos'
    | '/api/public/webhooks/whatsapp'
    | '/vendedor/veiculo/$id/proposta'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/comprador'
    | '/esqueci-minha-senha'
    | '/login'
    | '/redefinir-senha'
    | '/veiculos'
    | '/vendedor'
    | '/vender'
    | '/vistoriador'
    | '/admin/anuncios'
    | '/admin/compradores'
    | '/admin/comunicacoes'
    | '/admin/configuracoes'
    | '/admin/contratos'
    | '/admin/conversas'
    | '/admin/demo'
    | '/admin/entregas'
    | '/admin/logs'
    | '/admin/mapa'
    | '/admin/negociacoes'
    | '/admin/pagamentos'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/admin/veiculos'
    | '/admin/vendedores'
    | '/admin/vistorias'
    | '/comprador/cadastro'
    | '/comprador/documentos'
    | '/comprador/interesses'
    | '/comprador/negociacoes'
    | '/comprador/perfil'
    | '/veiculos/$slug'
    | '/vendedor/boas-vindas'
    | '/vendedor/cadastrar'
    | '/vendedor/contrato'
    | '/vendedor/documentos'
    | '/vendedor/financeiro'
    | '/vendedor/onboarding'
    | '/vendedor/perfil'
    | '/vendedor/veiculos'
    | '/vistoriador/agenda'
    | '/vistoriador/historico'
    | '/vistoriador/perfil'
    | '/admin/'
    | '/comprador/'
    | '/veiculos/'
    | '/vendedor/'
    | '/vistoriador/'
    | '/vendedor/veiculo/'
    | '/admin/analise-vistoria/$id'
    | '/admin/comprador/$id'
    | '/admin/contrato/$id'
    | '/admin/leiloes/$id'
    | '/admin/negociacao/$id'
    | '/admin/pagamento/$id'
    | '/admin/veiculo/$id'
    | '/admin/vendedor/$id'
    | '/api/public/upload'
    | '/comprador/entrega/$id'
    | '/comprador/pagamento/$id'
    | '/vendedor/entrega/$id'
    | '/vendedor/veiculo/$id'
    | '/vendedor/veiculo/proposta'
    | '/vistoriador/execucao/$id'
    | '/vistoriador/vistoria/$id'
    | '/admin/leiloes/'
    | '/admin/anuncios/novo/'
    | '/admin/veiculo/$id/pos-vistoria'
    | '/api/public/webhooks/pagamentos'
    | '/api/public/webhooks/whatsapp'
    | '/vendedor/veiculo/$id/proposta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CompradorRoute: typeof CompradorRouteWithChildren
  EsqueciMinhaSenhaRoute: typeof EsqueciMinhaSenhaRoute
  LoginRoute: typeof LoginRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  VeiculosRoute: typeof VeiculosRouteWithChildren
  VendedorRoute: typeof VendedorRouteWithChildren
  VenderRoute: typeof VenderRoute
  VistoriadorRoute: typeof VistoriadorRouteWithChildren
  ApiPublicUploadRoute: typeof ApiPublicUploadRoute
  ApiPublicWebhooksPagamentosRoute: typeof ApiPublicWebhooksPagamentosRoute
  ApiPublicWebhooksWhatsappRoute: typeof ApiPublicWebhooksWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprador': {
      id: '/comprador'
      path: '/comprador'
      fullPath: '/comprador'
      preLoaderRoute: typeof CompradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-minha-senha': {
      id: '/esqueci-minha-senha'
      path: '/esqueci-minha-senha'
      fullPath: '/esqueci-minha-senha'
      preLoaderRoute: typeof EsqueciMinhaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos': {
      id: '/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof VeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor': {
      id: '/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof VendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vender': {
      id: '/vender'
      path: '/vender'
      fullPath: '/vender'
      preLoaderRoute: typeof VenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vistoriador': {
      id: '/vistoriador'
      path: '/vistoriador'
      fullPath: '/vistoriador'
      preLoaderRoute: typeof VistoriadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/anuncios': {
      id: '/admin/anuncios'
      path: '/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AdminAnunciosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/compradores': {
      id: '/admin/compradores'
      path: '/compradores'
      fullPath: '/admin/compradores'
      preLoaderRoute: typeof AdminCompradoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comunicacoes': {
      id: '/admin/comunicacoes'
      path: '/comunicacoes'
      fullPath: '/admin/comunicacoes'
      preLoaderRoute: typeof AdminComunicacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contratos': {
      id: '/admin/contratos'
      path: '/contratos'
      fullPath: '/admin/contratos'
      preLoaderRoute: typeof AdminContratosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conversas': {
      id: '/admin/conversas'
      path: '/conversas'
      fullPath: '/admin/conversas'
      preLoaderRoute: typeof AdminConversasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/demo': {
      id: '/admin/demo'
      path: '/demo'
      fullPath: '/admin/demo'
      preLoaderRoute: typeof AdminDemoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entregas': {
      id: '/admin/entregas'
      path: '/entregas'
      fullPath: '/admin/entregas'
      preLoaderRoute: typeof AdminEntregasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mapa': {
      id: '/admin/mapa'
      path: '/mapa'
      fullPath: '/admin/mapa'
      preLoaderRoute: typeof AdminMapaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/negociacoes': {
      id: '/admin/negociacoes'
      path: '/negociacoes'
      fullPath: '/admin/negociacoes'
      preLoaderRoute: typeof AdminNegociacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/veiculos': {
      id: '/admin/veiculos'
      path: '/veiculos'
      fullPath: '/admin/veiculos'
      preLoaderRoute: typeof AdminVeiculosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendedores': {
      id: '/admin/vendedores'
      path: '/vendedores'
      fullPath: '/admin/vendedores'
      preLoaderRoute: typeof AdminVendedoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vistorias': {
      id: '/admin/vistorias'
      path: '/vistorias'
      fullPath: '/admin/vistorias'
      preLoaderRoute: typeof AdminVistoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/comprador/': {
      id: '/comprador/'
      path: '/'
      fullPath: '/comprador/'
      preLoaderRoute: typeof CompradorIndexRouteImport
      parentRoute: typeof CompradorRoute
    }
    '/comprador/cadastro': {
      id: '/comprador/cadastro'
      path: '/cadastro'
      fullPath: '/comprador/cadastro'
      preLoaderRoute: typeof CompradorCadastroRouteImport
      parentRoute: typeof CompradorRoute
    }
    '/comprador/documentos': {
      id: '/comprador/documentos'
      path: '/documentos'
      fullPath: '/comprador/documentos'
      preLoaderRoute: typeof CompradorDocumentosRouteImport
      parentRoute: typeof CompradorRoute
    }
    '/comprador/interesses': {
      id: '/comprador/interesses'
      path: '/interesses'
      fullPath: '/comprador/interesses'
      preLoaderRoute: typeof CompradorInteressesRouteImport
      parentRoute: typeof CompradorRoute
    }
    '/comprador/negociacoes': {
      id: '/comprador/negociacoes'
      path: '/negociacoes'
      fullPath: '/comprador/negociacoes'
      preLoaderRoute: typeof CompradorNegociacoesRouteImport
      parentRoute: typeof CompradorRoute
    }
    '/comprador/perfil': {
      id: '/comprador/perfil'
      path: '/perfil'
      fullPath: '/comprador/perfil'
      preLoaderRoute: typeof CompradorPerfilRouteImport
      parentRoute: typeof CompradorRoute
    }
    '/veiculos/': {
      id: '/veiculos/'
      path: '/'
      fullPath: '/veiculos/'
      preLoaderRoute: typeof VeiculosIndexRouteImport
      parentRoute: typeof VeiculosRoute
    }
    '/veiculos/$slug': {
      id: '/veiculos/$slug'
      path: '/$slug'
      fullPath: '/veiculos/$slug'
      preLoaderRoute: typeof VeiculosSlugRouteImport
      parentRoute: typeof VeiculosRoute
    }
    '/vendedor/': {
      id: '/vendedor/'
      path: '/'
      fullPath: '/vendedor/'
      preLoaderRoute: typeof VendedorIndexRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/vendedor/boas-vindas': {
      id: '/vendedor/boas-vindas'
      path: '/boas-vindas'
      fullPath: '/vendedor/boas-vindas'
      preLoaderRoute: typeof VendedorBoasVindasRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/vendedor/cadastrar': {
      id: '/vendedor/cadastrar'
      path: '/cadastrar'
      fullPath: '/vendedor/cadastrar'
      preLoaderRoute: typeof VendedorCadastrarRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/vendedor/contrato': {
      id: '/vendedor/contrato'
      path: '/contrato'
      fullPath: '/vendedor/contrato'
      preLoaderRoute: typeof VendedorContratoRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/vendedor/documentos': {
      id: '/vendedor/documentos'
      path: '/documentos'
      fullPath: '/vendedor/documentos'
      preLoaderRoute: typeof VendedorDocumentosRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/vendedor/financeiro': {
      id: '/vendedor/financeiro'
      path: '/financeiro'
      fullPath: '/vendedor/financeiro'
      preLoaderRoute: typeof VendedorFinanceiroRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/vendedor/onboarding': {
      id: '/vendedor/onboarding'
      path: '/onboarding'
      fullPath: '/vendedor/onboarding'
      preLoaderRoute: typeof VendedorOnboardingRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/vendedor/perfil': {
      id: '/vendedor/perfil'
      path: '/perfil'
      fullPath: '/vendedor/perfil'
      preLoaderRoute: typeof VendedorPerfilRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/vendedor/veiculos': {
      id: '/vendedor/veiculos'
      path: '/veiculos'
      fullPath: '/vendedor/veiculos'
      preLoaderRoute: typeof VendedorVeiculosRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/vistoriador/': {
      id: '/vistoriador/'
      path: '/'
      fullPath: '/vistoriador/'
      preLoaderRoute: typeof VistoriadorIndexRouteImport
      parentRoute: typeof VistoriadorRoute
    }
    '/vistoriador/agenda': {
      id: '/vistoriador/agenda'
      path: '/agenda'
      fullPath: '/vistoriador/agenda'
      preLoaderRoute: typeof VistoriadorAgendaRouteImport
      parentRoute: typeof VistoriadorRoute
    }
    '/vistoriador/historico': {
      id: '/vistoriador/historico'
      path: '/historico'
      fullPath: '/vistoriador/historico'
      preLoaderRoute: typeof VistoriadorHistoricoRouteImport
      parentRoute: typeof VistoriadorRoute
    }
    '/vistoriador/perfil': {
      id: '/vistoriador/perfil'
      path: '/perfil'
      fullPath: '/vistoriador/perfil'
      preLoaderRoute: typeof VistoriadorPerfilRouteImport
      parentRoute: typeof VistoriadorRoute
    }
    '/admin/analise-vistoria/$id': {
      id: '/admin/analise-vistoria/$id'
      path: '/analise-vistoria/$id'
      fullPath: '/admin/analise-vistoria/$id'
      preLoaderRoute: typeof AdminAnaliseVistoriaIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comprador/$id': {
      id: '/admin/comprador/$id'
      path: '/comprador/$id'
      fullPath: '/admin/comprador/$id'
      preLoaderRoute: typeof AdminCompradorIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contrato/$id': {
      id: '/admin/contrato/$id'
      path: '/contrato/$id'
      fullPath: '/admin/contrato/$id'
      preLoaderRoute: typeof AdminContratoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leiloes/': {
      id: '/admin/leiloes/'
      path: '/leiloes'
      fullPath: '/admin/leiloes/'
      preLoaderRoute: typeof AdminLeiloesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leiloes/$id': {
      id: '/admin/leiloes/$id'
      path: '/leiloes/$id'
      fullPath: '/admin/leiloes/$id'
      preLoaderRoute: typeof AdminLeiloesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/negociacao/$id': {
      id: '/admin/negociacao/$id'
      path: '/negociacao/$id'
      fullPath: '/admin/negociacao/$id'
      preLoaderRoute: typeof AdminNegociacaoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamento/$id': {
      id: '/admin/pagamento/$id'
      path: '/pagamento/$id'
      fullPath: '/admin/pagamento/$id'
      preLoaderRoute: typeof AdminPagamentoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/veiculo/$id': {
      id: '/admin/veiculo/$id'
      path: '/veiculo/$id'
      fullPath: '/admin/veiculo/$id'
      preLoaderRoute: typeof AdminVeiculoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendedor/$id': {
      id: '/admin/vendedor/$id'
      path: '/vendedor/$id'
      fullPath: '/admin/vendedor/$id'
      preLoaderRoute: typeof AdminVendedorIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/upload': {
      id: '/api/public/upload'
      path: '/api/public/upload'
      fullPath: '/api/public/upload'
      preLoaderRoute: typeof ApiPublicUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprador/entrega/$id': {
      id: '/comprador/entrega/$id'
      path: '/entrega/$id'
      fullPath: '/comprador/entrega/$id'
      preLoaderRoute: typeof CompradorEntregaIdRouteImport
      parentRoute: typeof CompradorRoute
    }
    '/comprador/pagamento/$id': {
      id: '/comprador/pagamento/$id'
      path: '/pagamento/$id'
      fullPath: '/comprador/pagamento/$id'
      preLoaderRoute: typeof CompradorPagamentoIdRouteImport
      parentRoute: typeof CompradorRoute
    }
    '/vendedor/entrega/$id': {
      id: '/vendedor/entrega/$id'
      path: '/entrega/$id'
      fullPath: '/vendedor/entrega/$id'
      preLoaderRoute: typeof VendedorEntregaIdRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/vendedor/veiculo/': {
      id: '/vendedor/veiculo/'
      path: '/veiculo'
      fullPath: '/vendedor/veiculo/'
      preLoaderRoute: typeof VendedorVeiculoRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/vendedor/veiculo/$id': {
      id: '/vendedor/veiculo/$id'
      path: '/veiculo/$id'
      fullPath: '/vendedor/veiculo/$id'
      preLoaderRoute: typeof VendedorVeiculoIdRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/vendedor/veiculo/proposta': {
      id: '/vendedor/veiculo/proposta'
      path: '/veiculo/proposta'
      fullPath: '/vendedor/veiculo/proposta'
      preLoaderRoute: typeof VendedorVeiculoPropostaRouteImport
      parentRoute: typeof VendedorRoute
    }
    '/vistoriador/execucao/$id': {
      id: '/vistoriador/execucao/$id'
      path: '/execucao/$id'
      fullPath: '/vistoriador/execucao/$id'
      preLoaderRoute: typeof VistoriadorExecucaoIdRouteImport
      parentRoute: typeof VistoriadorRoute
    }
    '/vistoriador/vistoria/$id': {
      id: '/vistoriador/vistoria/$id'
      path: '/vistoria/$id'
      fullPath: '/vistoriador/vistoria/$id'
      preLoaderRoute: typeof VistoriadorVistoriaIdRouteImport
      parentRoute: typeof VistoriadorRoute
    }
    '/admin/anuncios/novo/': {
      id: '/admin/anuncios/novo/'
      path: '/novo'
      fullPath: '/admin/anuncios/novo/'
      preLoaderRoute: typeof AdminAnunciosNovoRouteImport
      parentRoute: typeof AdminAnunciosRoute
    }
    '/admin/veiculo/$id/pos-vistoria': {
      id: '/admin/veiculo/$id/pos-vistoria'
      path: '/pos-vistoria'
      fullPath: '/admin/veiculo/$id/pos-vistoria'
      preLoaderRoute: typeof AdminVeiculoIdPosVistoriaRouteImport
      parentRoute: typeof AdminVeiculoIdRoute
    }
    '/api/public/webhooks/pagamentos': {
      id: '/api/public/webhooks/pagamentos'
      path: '/api/public/webhooks/pagamentos'
      fullPath: '/api/public/webhooks/pagamentos'
      preLoaderRoute: typeof ApiPublicWebhooksPagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/whatsapp': {
      id: '/api/public/webhooks/whatsapp'
      path: '/api/public/webhooks/whatsapp'
      fullPath: '/api/public/webhooks/whatsapp'
      preLoaderRoute: typeof ApiPublicWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendedor/veiculo/$id/proposta': {
      id: '/vendedor/veiculo/$id/proposta'
      path: '/proposta'
      fullPath: '/vendedor/veiculo/$id/proposta'
      preLoaderRoute: typeof VendedorVeiculoIdPropostaRouteImport
      parentRoute: typeof VendedorVeiculoIdRoute
    }
  }
}

interface AdminAnunciosRouteChildren {
  AdminAnunciosNovoRoute: typeof AdminAnunciosNovoRoute
}

const AdminAnunciosRouteChildren: AdminAnunciosRouteChildren = {
  AdminAnunciosNovoRoute: AdminAnunciosNovoRoute,
}

const AdminAnunciosRouteWithChildren = AdminAnunciosRoute._addFileChildren(
  AdminAnunciosRouteChildren,
)

interface AdminVeiculoIdRouteChildren {
  AdminVeiculoIdPosVistoriaRoute: typeof AdminVeiculoIdPosVistoriaRoute
}

const AdminVeiculoIdRouteChildren: AdminVeiculoIdRouteChildren = {
  AdminVeiculoIdPosVistoriaRoute: AdminVeiculoIdPosVistoriaRoute,
}

const AdminVeiculoIdRouteWithChildren = AdminVeiculoIdRoute._addFileChildren(
  AdminVeiculoIdRouteChildren,
)

interface AdminRouteChildren {
  AdminAnunciosRoute: typeof AdminAnunciosRouteWithChildren
  AdminCompradoresRoute: typeof AdminCompradoresRoute
  AdminComunicacoesRoute: typeof AdminComunicacoesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminContratosRoute: typeof AdminContratosRoute
  AdminConversasRoute: typeof AdminConversasRoute
  AdminDemoRoute: typeof AdminDemoRoute
  AdminEntregasRoute: typeof AdminEntregasRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMapaRoute: typeof AdminMapaRoute
  AdminNegociacoesRoute: typeof AdminNegociacoesRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminVeiculosRoute: typeof AdminVeiculosRoute
  AdminVendedoresRoute: typeof AdminVendedoresRoute
  AdminVistoriasRoute: typeof AdminVistoriasRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAnaliseVistoriaIdRoute: typeof AdminAnaliseVistoriaIdRoute
  AdminCompradorIdRoute: typeof AdminCompradorIdRoute
  AdminContratoIdRoute: typeof AdminContratoIdRoute
  AdminLeiloesIdRoute: typeof AdminLeiloesIdRoute
  AdminNegociacaoIdRoute: typeof AdminNegociacaoIdRoute
  AdminPagamentoIdRoute: typeof AdminPagamentoIdRoute
  AdminVeiculoIdRoute: typeof AdminVeiculoIdRouteWithChildren
  AdminVendedorIdRoute: typeof AdminVendedorIdRoute
  AdminLeiloesIndexRoute: typeof AdminLeiloesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnunciosRoute: AdminAnunciosRouteWithChildren,
  AdminCompradoresRoute: AdminCompradoresRoute,
  AdminComunicacoesRoute: AdminComunicacoesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminContratosRoute: AdminContratosRoute,
  AdminConversasRoute: AdminConversasRoute,
  AdminDemoRoute: AdminDemoRoute,
  AdminEntregasRoute: AdminEntregasRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMapaRoute: AdminMapaRoute,
  AdminNegociacoesRoute: AdminNegociacoesRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminVeiculosRoute: AdminVeiculosRoute,
  AdminVendedoresRoute: AdminVendedoresRoute,
  AdminVistoriasRoute: AdminVistoriasRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAnaliseVistoriaIdRoute: AdminAnaliseVistoriaIdRoute,
  AdminCompradorIdRoute: AdminCompradorIdRoute,
  AdminContratoIdRoute: AdminContratoIdRoute,
  AdminLeiloesIdRoute: AdminLeiloesIdRoute,
  AdminNegociacaoIdRoute: AdminNegociacaoIdRoute,
  AdminPagamentoIdRoute: AdminPagamentoIdRoute,
  AdminVeiculoIdRoute: AdminVeiculoIdRouteWithChildren,
  AdminVendedorIdRoute: AdminVendedorIdRoute,
  AdminLeiloesIndexRoute: AdminLeiloesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CompradorRouteChildren {
  CompradorCadastroRoute: typeof CompradorCadastroRoute
  CompradorDocumentosRoute: typeof CompradorDocumentosRoute
  CompradorInteressesRoute: typeof CompradorInteressesRoute
  CompradorNegociacoesRoute: typeof CompradorNegociacoesRoute
  CompradorPerfilRoute: typeof CompradorPerfilRoute
  CompradorIndexRoute: typeof CompradorIndexRoute
  CompradorEntregaIdRoute: typeof CompradorEntregaIdRoute
  CompradorPagamentoIdRoute: typeof CompradorPagamentoIdRoute
}

const CompradorRouteChildren: CompradorRouteChildren = {
  CompradorCadastroRoute: CompradorCadastroRoute,
  CompradorDocumentosRoute: CompradorDocumentosRoute,
  CompradorInteressesRoute: CompradorInteressesRoute,
  CompradorNegociacoesRoute: CompradorNegociacoesRoute,
  CompradorPerfilRoute: CompradorPerfilRoute,
  CompradorIndexRoute: CompradorIndexRoute,
  CompradorEntregaIdRoute: CompradorEntregaIdRoute,
  CompradorPagamentoIdRoute: CompradorPagamentoIdRoute,
}

const CompradorRouteWithChildren = CompradorRoute._addFileChildren(
  CompradorRouteChildren,
)

interface VeiculosRouteChildren {
  VeiculosSlugRoute: typeof VeiculosSlugRoute
  VeiculosIndexRoute: typeof VeiculosIndexRoute
}

const VeiculosRouteChildren: VeiculosRouteChildren = {
  VeiculosSlugRoute: VeiculosSlugRoute,
  VeiculosIndexRoute: VeiculosIndexRoute,
}

const VeiculosRouteWithChildren = VeiculosRoute._addFileChildren(
  VeiculosRouteChildren,
)

interface VendedorVeiculoIdRouteChildren {
  VendedorVeiculoIdPropostaRoute: typeof VendedorVeiculoIdPropostaRoute
}

const VendedorVeiculoIdRouteChildren: VendedorVeiculoIdRouteChildren = {
  VendedorVeiculoIdPropostaRoute: VendedorVeiculoIdPropostaRoute,
}

const VendedorVeiculoIdRouteWithChildren =
  VendedorVeiculoIdRoute._addFileChildren(VendedorVeiculoIdRouteChildren)

interface VendedorRouteChildren {
  VendedorBoasVindasRoute: typeof VendedorBoasVindasRoute
  VendedorCadastrarRoute: typeof VendedorCadastrarRoute
  VendedorContratoRoute: typeof VendedorContratoRoute
  VendedorDocumentosRoute: typeof VendedorDocumentosRoute
  VendedorFinanceiroRoute: typeof VendedorFinanceiroRoute
  VendedorOnboardingRoute: typeof VendedorOnboardingRoute
  VendedorPerfilRoute: typeof VendedorPerfilRoute
  VendedorVeiculosRoute: typeof VendedorVeiculosRoute
  VendedorIndexRoute: typeof VendedorIndexRoute
  VendedorVeiculoRoute: typeof VendedorVeiculoRoute
  VendedorEntregaIdRoute: typeof VendedorEntregaIdRoute
  VendedorVeiculoIdRoute: typeof VendedorVeiculoIdRouteWithChildren
  VendedorVeiculoPropostaRoute: typeof VendedorVeiculoPropostaRoute
}

const VendedorRouteChildren: VendedorRouteChildren = {
  VendedorBoasVindasRoute: VendedorBoasVindasRoute,
  VendedorCadastrarRoute: VendedorCadastrarRoute,
  VendedorContratoRoute: VendedorContratoRoute,
  VendedorDocumentosRoute: VendedorDocumentosRoute,
  VendedorFinanceiroRoute: VendedorFinanceiroRoute,
  VendedorOnboardingRoute: VendedorOnboardingRoute,
  VendedorPerfilRoute: VendedorPerfilRoute,
  VendedorVeiculosRoute: VendedorVeiculosRoute,
  VendedorIndexRoute: VendedorIndexRoute,
  VendedorVeiculoRoute: VendedorVeiculoRoute,
  VendedorEntregaIdRoute: VendedorEntregaIdRoute,
  VendedorVeiculoIdRoute: VendedorVeiculoIdRouteWithChildren,
  VendedorVeiculoPropostaRoute: VendedorVeiculoPropostaRoute,
}

const VendedorRouteWithChildren = VendedorRoute._addFileChildren(
  VendedorRouteChildren,
)

interface VistoriadorRouteChildren {
  VistoriadorAgendaRoute: typeof VistoriadorAgendaRoute
  VistoriadorHistoricoRoute: typeof VistoriadorHistoricoRoute
  VistoriadorPerfilRoute: typeof VistoriadorPerfilRoute
  VistoriadorIndexRoute: typeof VistoriadorIndexRoute
  VistoriadorExecucaoIdRoute: typeof VistoriadorExecucaoIdRoute
  VistoriadorVistoriaIdRoute: typeof VistoriadorVistoriaIdRoute
}

const VistoriadorRouteChildren: VistoriadorRouteChildren = {
  VistoriadorAgendaRoute: VistoriadorAgendaRoute,
  VistoriadorHistoricoRoute: VistoriadorHistoricoRoute,
  VistoriadorPerfilRoute: VistoriadorPerfilRoute,
  VistoriadorIndexRoute: VistoriadorIndexRoute,
  VistoriadorExecucaoIdRoute: VistoriadorExecucaoIdRoute,
  VistoriadorVistoriaIdRoute: VistoriadorVistoriaIdRoute,
}

const VistoriadorRouteWithChildren = VistoriadorRoute._addFileChildren(
  VistoriadorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CompradorRoute: CompradorRouteWithChildren,
  EsqueciMinhaSenhaRoute: EsqueciMinhaSenhaRoute,
  LoginRoute: LoginRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  VeiculosRoute: VeiculosRouteWithChildren,
  VendedorRoute: VendedorRouteWithChildren,
  VenderRoute: VenderRoute,
  VistoriadorRoute: VistoriadorRouteWithChildren,
  ApiPublicUploadRoute: ApiPublicUploadRoute,
  ApiPublicWebhooksPagamentosRoute: ApiPublicWebhooksPagamentosRoute,
  ApiPublicWebhooksWhatsappRoute: ApiPublicWebhooksWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
